### ISSUE TITLE
Calculating total price with tax is wrong

### ISSUE THREAD

**Issue by DavidLiedke** [akaunting/akaunting#185]
For example i had a article price of 465,20 € with the example tax of 5 %. 
Normal calculator: 465,20 * 1,05 = **488,46**
Akauting: 465,20 + 5 % tax = **488,25**

![firefox_2018-01-15_18-50-08](https://user-images.githubusercontent.com/25581728/34955504-fa200d8e-fa24-11e7-831c-3a71ef4b0e45.png)

Akauting is **only** calculating with **465,00 €**
![firefox_2018-01-15_18-50-08 - kopie](https://user-images.githubusercontent.com/25581728/34955777-3d425648-fa26-11e7-8898-f5cbc27bcdc2.png)

465 * 1,05 = 488,25

**Comment by cchoe1** [comment]
I investigated this a little and it seems that entering in amounts does not recognize commas (,), even though the display shows it with a comma.  Only periods are recognized to separate fractional amounts from whole Euros.  The functionality defaults to XXX.00 if you put a comma instead of a period, which is why it calculates based on 465.00 and not 465.20.  So it tries to find a 5% tax rate on 465.00 which is why it outputs 488.25.  

Essentially, the tax algorithm isn't messed up, per se, but it's just not recognizing the comma, so it assumes 0 change and only whole dollars.  I'll see if I can maybe fix this (I'm a little new to the whole package) but a workaround would be to use periods instead of commas, for now, until a fix is released.

**Comment by DavidLiedke** [comment]
> I'm not well versed in European practices--is it common to only use a comma for separating change or do you also use them as thousands separators, as well? 

No. They use periods for thousands and a comma for the rest. 

For example: 
1.100,99 €
10.300,95 €

**Comment by cchoe1** [comment]
Ok thanks, in my research I think I found a way to replace both commas and periods and format the currency properly, despite what currency you're currently working with (so it should work if the user is American and uses . for decimals and , for separators and also Europeans who use , for decimals and . for separators.  I'll try and get this updated asap and I'll post back in case the issue gets fixed at any point in time.

**Comment by Swagielka** [comment]
Hey there!
Are there any updates on this issue?
It appears that the problem still persists in the newest update. :)
